spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: market-server
            uri: ${MARKET_SERVER_URL:http://localhost:8083}
            predicates:
              - Path=/api/v1/stock/**, /api/v1/market/**

          - id: ai-server
            uri: ${AI_SERVER_URL:http://localhost:8084}
            predicates:
              - Path=/api/v1/ai/**

          - id: security-server
            uri: ${SECURITY_SERVER_URL:http://localhost:8080}
            predicates:
              - Path=/api/**

server:
  port: 8082
